name: com.example.flutter_cubit_app
description: A simple Flutter application that demonstrates the use of the Cubit pattern for state management.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0

dev_dependencies:
  bloc_test: ^9.0.3
  mocktail: ^0.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true